"""Preparation reports real work while preserving downloaded and generated bytes."""

from __future__ import annotations

import gzip
import hashlib
import io
from pathlib import Path

import pytest
from test_fetch import TINY_FA

from run_tests import fetch, progress


class FlushedOutput(io.StringIO):
    visible = ""

    def flush(self) -> None:
        self.visible = self.getvalue()


def test_progress_is_flushed_throttled_and_finishes(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    out = FlushedOutput()
    clock = [0.0]
    monkeypatch.setattr("sys.stdout", out)
    monkeypatch.setattr(progress.time, "monotonic", lambda: clock[0])
    bar = progress.Progress("Checking", 10)
    assert "0/10 bytes (0%)" in out.visible
    for done in range(1, 5):
        bar.update(done)
    assert len(out.visible.splitlines()) == 1
    clock[0] = 1.0
    bar.update(5)
    assert "5/10 bytes (50%)" in out.visible
    bar.update(10)
    bar.finish()
    assert len(out.visible.splitlines()) == 3
    assert "10/10 bytes (100%)" in out.visible


@pytest.mark.parametrize("length", [None, "7"])
def test_download_shows_progress_before_read_and_preserves_bytes(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, length: str | None
) -> None:
    out = FlushedOutput()
    clock = [0.0]
    monkeypatch.setattr("sys.stdout", out)
    monkeypatch.setattr(progress.time, "monotonic", lambda: clock[0])
    monkeypatch.setattr(fetch, "_CHUNK", 4)

    class Response(io.BytesIO):
        headers = {} if length is None else {"Content-Length": length}

        def read(self, size: int = -1) -> bytes:
            assert "Downloading reference FASTA" in out.visible
            if self.tell() == 0:
                assert "100%" not in out.visible
            clock[0] += 1
            return super().read(size)

    def open_url(url: str) -> Response:
        assert "total unknown" in out.visible  # visible even before connecting
        return Response(b"payload")

    monkeypatch.setattr("urllib.request.urlopen", open_url)
    target = tmp_path / "download.part"
    fetch.url_fetcher("https://example.invalid/reference.gz", target)
    assert target.read_bytes() == b"payload"
    assert "7/7 bytes (100%)" in out.visible
    assert (
        "4 bytes (total unknown)" if length is None else "4/7 bytes (57%)"
    ) in out.visible


def test_fasta_preparation_stages_and_warm_reuse_preserve_output(
    tmp_path: Path,
) -> None:
    archive = gzip.compress(TINY_FA)
    source = tmp_path / "source.gz"
    source.write_bytes(archive)
    checksum, blocks = fetch.bsd_sum(source)
    pin = fetch.FastaPin(
        url="https://example.invalid/reference.fa.gz",
        sha256_fa=hashlib.sha256(TINY_FA).hexdigest(),
        ensembl_sum=f"{checksum} {blocks}",
    )
    lines: list[str] = []
    downloads = []

    def download(url: str, destination: Path) -> None:
        downloads.append(url)
        destination.write_bytes(archive)

    root = tmp_path / "fasta"
    fetch.fetch_fasta(root, pin, download, out=lines.append)
    stages = [
        "Checking FASTA archive checksum",
        "Decompressing reference FASTA",
        "Indexing reference FASTA",
        "Verifying reference FASTA SHA-256",
    ]
    assert [line.split(" [")[0] for line in lines] == [
        s for s in stages for _ in range(2)
    ]
    assert all("(0%)" in line for line in lines[::2])
    assert all("(100%)" in line for line in lines[1::2])
    fa = root / pin.fa_name
    assert fa.read_bytes() == TINY_FA
    index = Path(str(fa) + ".fai").read_bytes()
    assert index
    lines.clear()
    fetch.fetch_fasta(root, pin, download, out=lines.append)
    assert downloads == [pin.url]
    assert len(lines) == 2 and all(line.startswith(stages[-1]) for line in lines)
    assert fa.read_bytes() == TINY_FA
    assert Path(str(fa) + ".fai").read_bytes() == index
